config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'cart/:id' => 'store#save_to_cart', as: 'add_to_cart'

  post 'clear_cart' => 'store#clear_cart'

  post 'create_customer' => 'store#checkout_customer', as: 'checkout_customer'

  get 'products/:id' => 'store#product', as: 'product'

  get 'show' => 'store#product'

  get 'about' => 'pages#about_view'

  get 'contact' => 'pages#contact_view'

  get 'cart' => 'store#cart'

  get 'checkout' => 'store#checkout', as: 'start_checkout'

  get 'checkout' => 'store#checkout', as: 'complete_checkout'

  root to: 'store#index'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :my_resources, :concerns => :paginatable

end

app/views/shared/_cart_item.html.erb
<div class="cart_item panel panel-success">
  <div class="panel-body">
    <%= image_tag(product[:item].image, class: 'cart_item_image') %>
    <%= link_to(truncate(product[:item].name, :length => 75), product_path(product[:item])) %>
    <div class="item-info">
      Qty: <input type="text" class="qty-box" value="<%= product[:qty] %>" />
      <h4><%= number_to_currency(product[:item].price) %></h4>
    </div>
  </div>
</div>

app/views/shared/_features_bar.html.erb
<div id="features_bar">
  <% @featured_products.each do |product| %>
    <div class="featured_item">
      <% image_tag @products.(:product_id).image %>
      <% @products.(:product_id).name %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p>Copywrong <a href="http://www.tophatsolutions.ca">TopHat Solutions</a></p>
</footer>

app/views/shared/_header.html.erb
<header>
  <h3><%= link_to "The Urban Sloth", root_path %></h3>
  <span class="user_info">Hi! Log in | Register</span>
</header>

app/views/shared/_mini_cart.html.erb
<div id="mini_cart" class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to 'Your Cart', cart_path %></h3>
    <%= link_to 'Clear Cart', clear_cart_path, method: 'post' %>
  </div>
  <div class="panel-body">

    <%= render  partial: 'shared/mini_cart_item',
                collection: @cart_items,
                as: 'product' %>
    <span class="link-to-cart"><%= link_to 'Go to Cart', cart_path %></span>
  </div>
  <div class="panel-footer">
    <h3>SubTotal: <%= number_to_currency(@subtotal) %></h3>
  </div>
</div>

app/views/shared/_mini_cart_item.html.erb
<div class="cart_item">
  <%= image_tag(product[:item].image, class: 'cart_item_image') %>
  <%= link_to(truncate(product[:item].name, :length => 25), product_path(product[:item])) %>
  <h4><%= product[:qty] %> x <%= number_to_currency(product[:item].price) %></h4>
</div>

app/views/shared/_navigation.html.erb
<nav id="site_nav">
  <ul  class="btn-group">
    <li><%= link_to 'Home', root_path, class: "btn btn-default"%></li>
    <li><%= link_to 'About', about_path, class: "btn btn-default" %></li>
    <li><%= link_to 'Contact', contact_path, class: "btn btn-default" %></li>
    <% if @cart %>
      <li>
        <%= link_to (cart_path), class: "btn btn-default" do %>
          Cart <span class="badge"><%= @cart.count %>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_product.html.erb
<div class="product">
  <div class="product_img">
    <%= link_to(image_tag(product.image), product)%>
  </div>
  <h5><%= link_to(product.name, product) %></h5>
  <ul>
    <li><%= product.sell_point_1 %></li>
    <li><%= product.sell_point_2 %></li>
    <li><%= product.sell_point_3 %></li>
  </ul>
  <h4><%= number_to_currency(product.price) %></h4>
  <%= link_to 'Add to Cart', add_to_cart_path(product.id), method: 'post', class: 'btn btn-danger' %>
</div>

app/views/shared/_search_bar.html.erb
<%= form_for @filterrific, :html => {class: 'search_form'} do |f| %>
  <div id="search_bar" class="input-group">
    <div class="input-group-btn">
      <%= f.select(
        :with_category_id,
        @filterrific.select_options[:with_category_id],
        {include_blank: 'All Categories'},
        class: 'filterrific-periodically-observed btn btn-primary'
      ) %>
    </div>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed form-control',
      placeholder: 'Search'
    ) %>
  </div>
  <div id="store_selector">
    <%#= f.select(
    :with_lifestyle_id,
    @filterrific.select_options[:with_lifestyle_id],
    {include_blank: 'All Lifestyles'}
    ) %>
    <label>Sort By </label>
    <%= f.select(
      :sorted_by,
      @filterrific.select_options[:sorted_by],
      {},
      class: 'filterrific-periodically-observed btn btn-info btn-sm'
    ) %>
  </div>
  <%= render_filterrific_spinner %>
<% end %>

app/views/shared/_show_products.html.erb
<h4>Store: </h4>
<form method="post">
  <select name="lifestyle">
    <option>All Lifestyles</option>
    <% all_lifestyles.each do |lifestyle| %>
      <option value="<%= lifestyle.id %>"><%= lifestyle.name %></option>
    <% end %>
  </select>
</form>

app/views/shared/_store_selector.html.erb
<div id="store_selector">
  <h4>Store: </h4>
  <%= form_for @filterrific do |f| %>
    <%= f.select(
      :with_lifestyle_id,
      @filterrific.select_options[:with_lifestyle_id],
      {include_blank: 'All Lifestyles'}
    ) %>
    <h4>View: </h4>
    <%= f.select(
      :sorted_by,
      @filterrific.select_options[:sorted_by],
      class: 'filterrific-periodically-observed'
    ) %>

  <% end %>
  <%# selected_filters.each do |filter| %>
    <a href="<%#= filter.destroy %>"><%#= filter.name %></a>
  <%# end %>
</div>