config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'cart/:id' => 'store#save_to_cart', as: 'add_to_cart'

  post 'clear_cart' => 'store#clear_cart'

  post 'create_customer' => 'store#checkout_customer', as: 'checkout_customer'

  get 'products/:id' => 'store#product', as: 'product'

  get 'show' => 'store#product'

  get 'about' => 'pages#about_view'

  get 'contact' => 'pages#contact_view'

  get 'cart' => 'store#cart'

  get 'checkout' => 'store#checkout', as: 'start_checkout'

  get 'checkout' => 'store#checkout', as: 'complete_checkout'

  root to: 'store#index'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :my_resources, :concerns => :paginatable

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_action :grab_cart_items

  # paginates_per 8
  def index
    @show_progress = true
    @show_progress_max = 115
    @show_progress_goal = 100
    @show_progress_amt = 110
    @show_progress_percent = ((@show_progress_amt.to_f / @show_progress_max) * 100).to_i
    @show_progress_left_for_possible = (@show_progress_goal - @show_progress_percent).round
    @show_progress_left_for_goal = @show_progress_goal - @show_progress_amt
    @cart_subtotal = 0.00

    @sale_products = Product.where(sale: true)

    if session[:visit_count]
      @visit_count = session[:visit_count] + 1
    else
      @visit_count = 1
    end
    session[:visit_count] = @visit_count

    @filterrific = Filterrific.new(Product, params[:filterrific] || session[:filterrific_products])
    @products = Product.filterrific_find(@filterrific).page(params[:page]).per(8)
    @sale_products = Product.where(sale: true)

    @filterrific.select_options = {
      with_lifestyle_id: Lifestyle.options_for_select,
      with_category_id: Category.options_for_select,
      sorted_by: Product.options_for_select
    }

    session[:filterrific_products] = @filterrific.to_hash

    respond_to do |format|
      format.html
      format.js
    end

    rescue ActiveRecord::RecordNotFound => e
      # There is an issue with the persisted param_set. Reset it.
      Logger "Had to reset filterrific params: #{ e.message }"
      redirect_to(action: :reset_filterrific, format: :html) && return
  end

  def cart
    @cart_subtotal = session[:subtotal]
    @customer = Customer.find(session[:customer_id].to_i) unless session[:customer_id].nil?

    #@cart_items = []
    #if @cart
    #  @cart.each do |id|
    #    @cart_items.push(Product.find(id))
    #  end
    #end
    #session[:subtotal] = @cart_subtotal
  end

  def checkout
    if session[:customer_id]
      @customer = Customer.find(session[:customer_id])

      order = @customer.orders.build

      order.status = 'new'
      order.pst_rate = @customer.province.pst_rate
      order.gst_rate = @customer.province.gst_rate
      order.hst_rate = @customer.province.hst_rate
      order.sub_total = session[:subtotal]

      order.total = order.sub_total +
        (order.sub_total * order.pst_rate) +
        (order.sub_total * order.gst_rate) +
        (order.sub_total * order.hst_rate)
      respond_to do |format|
        if order.save
          # Logger 'Order Saved.'
          @cart_items.each do |product|

            # Logger product.name
            line_item = order.line_items.build
            line_item.product = product[:item]
            line_item.quantity = 1
            line_item.price = product[:item].price

            if line_item.save
              # Logger "#{product.name} Saved."
            else
              # Logger 'Error: '
              line_item.errors.messages.each do |column, errors|
                errors.each do |error|
                  Logger "The #{column} property #{error}."
                end
              end
            end
          end
          session[:cart] = nil
          session[:customer_id] = nil
          format.html { redirect_to root_path, notice: 'You Have Successfully Placed Your Order.' }
          format.json { render :show, status: :created, location: @customer }
        else
          # Logger 'Error: '
          order.errors.messages.each do |column, errors|
            errors.each do |error|
              # Logger "The #{column} property #{error}."
            end
          end
        end
      end
    else
      @customer = Customer.new
    end
  end

  def checkout_customer
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        session[:customer_id] = @customer.id
        format.html { redirect_to cart_path, notice: 'You Have Successfully Signed Up.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def product
    @product = Product.find_by_slug(params[:id])
    @cart_subtotal = 0.0
    if session[:subtotal]
      @cart_subtotal = session[:subtotal]
    end
  end

  def grab_cart_items
    if session[:cart]
      @subtotal = 0.00
      @cart = session[:cart]
      @cart_items = []
      @cart.each do |id|
        @id = id['id']
        item = Product.find(@id)
        @cart_items.push({item: item, qty: id['qty']})
        @subtotal += item.price * id['qty']
      end
      session[:subtotal] = @subtotal
    else
      return 'No Items in Cart'
    end
  end

  def clear_cart
    session[:cart] = nil
    session[:subtotal] = nil
    @cart = nil
    redirect_to :back
  end

  def save_to_cart
    @id = params[:id].to_i
    if session[:cart]
      @cart = session[:cart]
      if @cart.any? {|i| i['id'] == @id}
        @cart.each do |i|
          if i['id'] == @id
            i['qty'] += 1
          end
        end
      else
        @cart.push({:id => @id, :qty => 1})
      end

    else
      @cart = []
      @cart.push({:id => @id, :qty => 1})
    end
    session[:cart] = @cart
    redirect_to :back
  end

  private

  def customer_params
    params.require(:customer).permit(
      :full_name,
      :phone_number,
      :email_address,
      :street_address,
      :postal_code,
      :province_id
    )
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/cart.html.erb
<div id="page_cart">
  <h2>Your Cart</h2>
  <% if @cart %>
    <%= link_to 'Clear Cart', clear_cart_path, method: 'post' %>
    <%# get_cart_items %>
    <%= render  partial: 'shared/cart_item',
                collection: @cart_items,
                as: 'product' %>
    <div id="cart_totals_box">
      <h4>SubTotal: <%= number_to_currency(@cart_subtotal) %></h4>
      <% if @customer %>
        <% if !@customer.province.pst_rate.zero? %>
          <% pst_rate = @customer.province.pst_rate %>
          <h4>PST (<%= pst_rate*100 %>%): <%= number_to_currency(pst = pst_rate * @cart_subtotal) %></h4>
        <% else %>
          <% pst = 0.0 %>
        <% end %>
        <% if !@customer.province.pst_rate.zero? %>
          <% gst_rate = @customer.province.gst_rate %>
          <h4>GST (<%= gst_rate*100 %>%): <%= number_to_currency(gst = gst_rate * @cart_subtotal) %></h4>
        <% else %>
          <% gst = 0.0 %>
        <% end %>
        <% if !@customer.province.hst_rate.zero? %>
          <% hst_rate = @customer.province.hst_rate %>
          <h4>HST (<%= hst_rate*100 %>%): <%= number_to_currency(hst = hst_rate * @cart_subtotal) %></h4>
        <% else %>
          <% hst = 0.0 %>
        <% end %>
      <% end %>
      <% @cart_total = @cart_subtotal + (pst) + (gst) + (hst) unless !@customer %>
      <% if @customer %>
        <h3>Total: <%= number_to_currency(@cart_total) %></h3>
      <% end %>
    </div>
    <div id="checkout_box">
      <% if @customer.nil? %>
        <%= link_to 'Proceed to Sign In', start_checkout_path, class: 'btn btn-warning' %>
      <% else %>
        <%= link_to 'Complete Checkout', complete_checkout_path, class: 'btn btn-success' %>
      <% end %>
    </div>
  <% else %>
    <div class="alert alert-warning">
      There are no items in your cart!
      <%= link_to 'Back to Store', root_path, class: 'btn btn-sm btn-warning right-align'%>
    </div>
  <% end %>
</div>

app/views/store/checkout.html.erb
<div id="checkout_signin_form">
  <%= semantic_form_for @customer, :url => checkout_customer_path, :html => {:method => :post}, :remote => false do |f| %>
    <%=  f.inputs do %>
      <%=  f.input :full_name, :required => true %>
      <%=  f.input :phone_number, :required => true %>
      <%=  f.input :email_address, :required => true %>
      <%=  f.input :street_address, :required => true %>
      <%=  f.input :postal_code, :required => true %>
      <%=  f.input :province, :required => true %>
    <% end %>
    <%= f.actions do %>
      <%= f.action :submit, :as => :button, :label => 'Sign Up', :button_html => {:class => 'btn btn-warning'} %>
    <% end %>
  <% end %>
</div>

app/views/store/index.html.erb
<% #render "shared/features_bar" %>
<%= render "shared/search_bar" %>
<%#= render "shared/store_selector" %>
<%= render  'shared/mini_cart' unless @cart.nil? %>
<%#= @cart %>
<%# @cart.each do |item| %>
<%#= item['id'] %>
<%#= item['qty'] %>
<%# end unless @cart.nil?%>
<%#= @cart_items %>
<%#= @cart_items[0][:item].name %>
<div id="store_product_display">
  <aside id="filters">
    <section id="filter_by_categories">
      <h5>Categories: </h5>
      <ul>
        <% all_categories.each do |category| %>
          <li><%= category.name %></li>
        <% end %>
      </ul>
    </section>
    <section id="filter_by_filters">
      <h5>Brands: </h5>
      <ul>
        <% all_brands.each do |brand| %>
          <li><%= brand.name %></li>
        <% end %>
      </ul>
    </section>
  </aside>
  <div id="products_to_display">
    <% if @sale_products.count > 0 %>
      <section id="sale_products">
        <h3>Sale Products</h3>
        <%= render partial: 'shared/sale_products',
                   collection: @sale_products,
                   as: 'product' %>
      </section>
    <% end %>
    <% if @products.count > 0 %>
      <section id="all_products">
        <h3>Products</h3>
        <div id="filterrific_results">
          <%= render partial: 'shared/product',
                     collection: @products,
                     as: 'product' %>
        </div>
      </section>
      <%= paginate @products %>
    <% else %>
      <section id="no_products_found">
        <div class="alert alert-danger" role="alert">Unfortunately, no products were found matching those parameters, check your settings and try again!</div>
      </section>
    <% end %>
  </div>
  <div id="bottom-holder">
    <p> </p>
  </div>
</div>

app/views/store/index.js.erb
<%# app/views/students/index.js.erb %>
<% js = escape_javascript(
render(partial: 'shared/product', locals: { products: @products })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/store/product.html.erb
<%= render  'shared/mini_cart' unless @cart.nil? %>
<p id="notice"><%= notice %></p>
<div id="product_page">
  <div class="product_image">
    <%= image_tag(@product.image) unless !@product %>
  </div>
  <div id="product_info">
    <h1><%= @product.name unless !@product%></h1>
    <h3><%= @product.title unless !@product%></h3>
    <h2><%= number_to_currency(@product.price) unless !@product%></h2>
    <%= link_to 'Add to Cart', add_to_cart_path(@product.id), method: 'post', class: 'btn btn-danger add_to_cart_btn' %>
    <div id="product_features">
      <h3>Key Features:</h3>
      <ul>
        <li><%= @product.sell_point_1 unless !@product%></li>
        <li><%= @product.sell_point_2 unless !@product%></li>
        <li><%= @product.sell_point_3 unless !@product%></li>
      </ul>
    </div>
  </div>
  <br />
  <div id="product_description">
    <h3>Description:</h3>
    <%= @product.description.html_safe unless !@product%>
  </div>
</div>